server:
  port: 9093
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: java14user
    password: root
  datasource:
    url: jdbc:postgresql://localhost:5432/livesupportDB
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true