server:
  port: 9095

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/NotificationDB
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: java14user
    password: root
