server:
  port: 9097
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: java14user
    password: root
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/userDB
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true